# Generated by Django 4.1.3 on 2023-01-05 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppConfig",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("layout", models.CharField(default="", max_length=25)),
                ("scheme", models.CharField(default="", max_length=25)),
                ("theme", models.CharField(default="", max_length=25)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "App config",
                "verbose_name_plural": "App configs",
                "db_table": "user_config",
            },
        ),
    ]
