# Generated by Django 4.2.7 on 2023-11-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0002_customer_charge_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="mobile",
            field=models.CharField(blank=True, default="", max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="reference",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
