# Generated by Django 4.2.1 on 2023-05-18 21:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='StaffVetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateField(blank=True, null=True)),
                ('ended', models.DateField(blank=True, null=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vetting', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Vetting',
                'verbose_name_plural': 'Vetting',
                'db_table': 'staff_vetting',
            },
        ),
        migrations.CreateModel(
            name='StaffReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('post_code', models.CharField(blank=True, max_length=50, null=True)),
                ('occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('how_long', models.CharField(blank=True, max_length=50, null=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Reference',
                'verbose_name_plural': 'References',
                'db_table': 'staff_reference',
            },
        ),
        migrations.CreateModel(
            name='StaffPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Staff Phone',
                'verbose_name_plural': 'Staff Phones',
                'db_table': 'staff_phone',
            },
        ),
        migrations.CreateModel(
            name='StaffPassort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('document_no', models.CharField(blank=True, max_length=50, null=True)),
                ('entry_uk', models.DateField(blank=True, null=True)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('issue', models.DateField(blank=True, null=True)),
                ('visa_expiry', models.DateField(blank=True, null=True)),
                ('visa_issue', models.DateField(blank=True, null=True)),
                ('visa_needed', models.BooleanField(default=False)),
                ('visa_type', models.CharField(blank=True, max_length=50, null=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passport', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Passport',
                'verbose_name_plural': 'Passports',
                'db_table': 'staff_passport',
            },
        ),
        migrations.CreateModel(
            name='StaffEmployer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_from', models.DateField(blank=True, null=True)),
                ('_until', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('post_code', models.CharField(blank=True, max_length=50, null=True)),
                ('reason', models.CharField(blank=True, max_length=50, null=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Employer',
                'verbose_name_plural': 'Employers',
                'db_table': 'staff_employer',
            },
        ),
        migrations.CreateModel(
            name='StaffEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Staff Email',
                'verbose_name_plural': 'Staff Emails',
                'db_table': 'staff_email',
            },
        ),
        migrations.CreateModel(
            name='StaffEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_from', models.DateField(blank=True, null=True)),
                ('_until', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('institute', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('speciality', models.CharField(blank=True, max_length=50, null=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Degree',
                'verbose_name_plural': 'Degrees',
                'db_table': 'staff_education',
            },
        ),
        migrations.CreateModel(
            name='StaffDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('driving_licence', models.CharField(blank=True, max_length=50, null=True)),
                ('ethnic_origin', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('is_driving', models.BooleanField(default=False)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('ni_number', models.CharField(blank=True, max_length=50, null=True)),
                ('pay_rate', models.FloatField(blank=True, null=True)),
                ('pin', models.CharField(blank=True, max_length=50, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=50, null=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Details',
                'verbose_name_plural': 'Details',
                'db_table': 'staff_details',
            },
        ),
        migrations.CreateModel(
            name='StaffContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateField(blank=True, null=True)),
                ('ended', models.DateField(blank=True, null=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'db_table': 'staff_contract',
            },
        ),
        migrations.CreateModel(
            name='StaffContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('post_code', models.CharField(blank=True, max_length=50, null=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'verbose_name_plural': 'Emergency Contacts',
                'db_table': 'staff_contacts',
            },
        ),
        migrations.CreateModel(
            name='StaffBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('account_title', models.CharField(blank=True, max_length=50, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('sort_code', models.CharField(blank=True, max_length=50, null=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Bank Details',
                'verbose_name_plural': 'Bank Details',
                'db_table': 'staff_bank',
            },
        ),
        migrations.CreateModel(
            name='StaffAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=30)),
                ('post_code', models.CharField(max_length=15)),
                ('_from', models.DateField(blank=True, null=True)),
                ('_until', models.DateField(blank=True, null=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Address',
                'db_table': 'staff_address',
            },
        ),
    ]
