# Generated by Django 4.2.1 on 2023-05-18 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absent_days', models.CharField(blank=True, max_length=50, null=True)),
                ('additional_comment', models.CharField(blank=True, max_length=225, null=True)),
                ('any_other', models.CharField(blank=True, max_length=225, null=True)),
                ('can_be_examined', models.BooleanField(blank=True, null=True)),
                ('glasses', models.BooleanField(blank=True, null=True)),
                ('has_condition', models.BooleanField(blank=True, null=True)),
                ('heart_disease', models.BooleanField(blank=True, null=True)),
                ('is_diabetec', models.BooleanField(blank=True, null=True)),
                ('is_disabled', models.BooleanField(blank=True, null=True)),
                ('needs_carer', models.BooleanField(blank=True, null=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Health',
                'verbose_name_plural': 'Health',
                'db_table': 'staff_health',
            },
        ),
        migrations.CreateModel(
            name='StaffAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bust', models.CharField(blank=True, max_length=50, null=True)),
                ('chest', models.CharField(blank=True, max_length=50, null=True)),
                ('collar', models.CharField(blank=True, max_length=50, null=True)),
                ('eye_colour', models.CharField(blank=True, max_length=50, null=True)),
                ('facial_hair', models.CharField(blank=True, max_length=50, null=True)),
                ('hair_colour', models.CharField(blank=True, max_length=50, null=True)),
                ('hair_length', models.CharField(blank=True, max_length=50, null=True)),
                ('hat_size', models.CharField(blank=True, max_length=50, null=True)),
                ('height', models.CharField(blank=True, max_length=50, null=True)),
                ('hips', models.CharField(blank=True, max_length=50, null=True)),
                ('inside_leg', models.CharField(blank=True, max_length=50, null=True)),
                ('jacket_size', models.CharField(blank=True, max_length=50, null=True)),
                ('shoe_size', models.CharField(blank=True, max_length=50, null=True)),
                ('skirt_size', models.CharField(blank=True, max_length=50, null=True)),
                ('trousers_size', models.CharField(blank=True, max_length=50, null=True)),
                ('waist', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appearance', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Appearance',
                'verbose_name_plural': 'Appearances',
                'db_table': 'staff_appearance',
            },
        ),
    ]
