# Generated by Django 4.2.1 on 2023-05-19 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staffhealth_staffappearance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ('name',), 'verbose_name': 'Staff', 'verbose_name_plural': 'Staff'},
        ),
        migrations.RenameField(
            model_name='staffaddress',
            old_name='_from',
            new_name='in_from',
        ),
        migrations.RenameField(
            model_name='staffaddress',
            old_name='_until',
            new_name='in_until',
        ),
    ]
