# Generated by Django 4.2.1 on 2023-05-19 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staff_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffaddress',
            old_name='in_until',
            new_name='in_untill',
        ),
    ]
