# Generated by Django 4.2.1 on 2023-05-29 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_rename_in_until_staffaddress_in_untill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffaddress',
            options={'ordering': ('-in_untill', '-in_from'), 'verbose_name': 'Address', 'verbose_name_plural': 'Address'},
        ),
    ]
