# Generated by Django 4.2.1 on 2023-05-30 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_staffaddress_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffLicence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_no', models.CharField(blank=True, max_length=50, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=80, null=True)),
                ('registered', models.DateField(blank=True, null=True)),
                ('licence_sector', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=80, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(blank=True, max_length=100, null=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licence', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Licence',
                'verbose_name_plural': 'Licences',
                'db_table': 'staff_licence',
            },
        ),
    ]
