# Generated by Django 4.2.1 on 2023-05-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_stafflicence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stafflicence',
            old_name='surname',
            new_name='last_name',
        ),
    ]
