# Generated by Django 4.2.1 on 2023-06-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_rename_surname_stafflicence_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='pay_rate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
