# Generated by Django 4.2.1 on 2023-06-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_staff_pay_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='pay_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
