# Generated by Django 4.1.3 on 2023-01-05 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserShortcuts",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(default="", max_length=50)),
                ("description", models.CharField(default="", max_length=100)),
                ("icon", models.CharField(default="", max_length=50)),
                ("link", models.CharField(default="", max_length=100)),
                ("useRouter", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shortcuts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User shortcut",
                "verbose_name_plural": "User shortcuts",
                "db_table": "user_shortcuts",
            },
        ),
    ]
