# Generated by Django 4.1.3 on 2022-12-22 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChildNavigation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default="", max_length=50, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=50)),
                ("icon", models.CharField(default="", max_length=50)),
                ("type", models.CharField(blank=True, default="basic", max_length=15)),
                ("hidden", models.BooleanField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("disabled", models.BooleanField(blank=True)),
                ("tooltip", models.CharField(blank=True, max_length=50)),
                ("link", models.CharField(default="", max_length=50)),
                ("fragment", models.CharField(blank=True, max_length=50)),
                ("preserveFragment", models.BooleanField(blank=True)),
                ("externalLink", models.BooleanField(blank=True)),
                ("target", models.CharField(blank=True, max_length=50)),
                ("exactMatch", models.BooleanField(blank=True)),
                ("meta", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name": "Child Navigation",
                "verbose_name_plural": "Child Navigation",
                "db_table": "child_navigation",
            },
        ),
        migrations.CreateModel(
            name="MainNavigation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default="", max_length=50, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=50)),
                ("icon", models.CharField(default="", max_length=50)),
                ("subtitle", models.CharField(blank=True, max_length=50)),
                ("type", models.CharField(default="group", max_length=15)),
            ],
            options={
                "verbose_name": "Main Navigation",
                "verbose_name_plural": "Main Navigation",
                "db_table": "main_navigation",
            },
        ),
        migrations.CreateModel(
            name="ChildNavigationClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=50)),
                ("subtitle", models.CharField(blank=True, max_length=50)),
                ("icon", models.CharField(default="", max_length=50)),
                ("wrapper", models.CharField(default="", max_length=50)),
                (
                    "navigation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="navigation.childnavigation",
                    ),
                ),
            ],
            options={
                "db_table": "child_navigation_class",
            },
        ),
        migrations.CreateModel(
            name="ChildNavigationBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=50)),
                ("classes", models.CharField(default="", max_length=50)),
                (
                    "Navigation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badge",
                        to="navigation.childnavigation",
                    ),
                ),
            ],
            options={
                "db_table": "child_navigation_badge",
            },
        ),
        migrations.AddField(
            model_name="childnavigation",
            name="main",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="navigation.mainnavigation",
            ),
        ),
    ]
