# Generated by Django 4.1.3 on 2023-01-05 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Navigation",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(blank=True, max_length=255)),
                ("icon", models.CharField(default="", max_length=255)),
                ("link", models.CharField(blank=True, max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("aside", "Aside"),
                            ("basic", "Basic"),
                            ("collapsable", "Collapsable"),
                            ("divider", "Divider"),
                            ("group", "Group"),
                            ("spacer", "Spacer"),
                        ],
                        max_length=255,
                    ),
                ),
                ("hidden", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=False)),
                ("disabled", models.BooleanField(default=False)),
                ("tooltip", models.CharField(blank=True, max_length=255)),
                ("fragment", models.CharField(blank=True, max_length=255)),
                ("preserve_fragment", models.BooleanField(default=False)),
                ("query_params", models.TextField(blank=True)),
                ("query_params_handling", models.CharField(blank=True, max_length=255)),
                ("external_link", models.BooleanField(default=False)),
                (
                    "target",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("_blank", "Blank"),
                            ("_self", "Self"),
                            ("_parent", "Parent"),
                            ("_top", "Top"),
                        ],
                        max_length=255,
                    ),
                ),
                ("exact_match", models.BooleanField(default=False)),
                ("is_active_match_options", models.TextField(blank=True)),
                ("function", models.TextField(blank=True)),
                ("classes", models.TextField(blank=True)),
                ("badge", models.TextField(blank=True)),
                ("meta", models.TextField(blank=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="navigation.navigation",
                    ),
                ),
                (
                    "visible_to",
                    models.ForeignKey(
                        blank=True,
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Navigation Item",
                "verbose_name_plural": "Navigation Items",
                "db_table": "navigations",
            },
        ),
    ]
