# Generated by Django 4.1.3 on 2022-12-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childnavigation",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="mainnavigation",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
