# Generated by Django 4.1.3 on 2022-12-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="childnavigation",
            name="subtitle",
        ),
        migrations.AlterField(
            model_name="childnavigation",
            name="type",
            field=models.CharField(blank=True, default="basic", max_length=15),
        ),
    ]
