# Generated by Django 4.1.3 on 2022-12-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0002_remove_childnavigation_subtitle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childnavigation",
            name="disabled",
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name="childnavigation",
            name="fragment",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="childnavigation",
            name="hidden",
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name="childnavigation",
            name="meta",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="childnavigation",
            name="target",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="childnavigation",
            name="tooltip",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
