# Generated by Django 4.1.3 on 2022-12-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("navigation", "0002_alter_childnavigation_id_alter_mainnavigation_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Navigation",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(blank=True, max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("aside", "Aside"),
                            ("basic", "Basic"),
                            ("collapsable", "Collapsable"),
                            ("divider", "Divider"),
                            ("group", "Group"),
                            ("spacer", "Spacer"),
                        ],
                        max_length=255,
                    ),
                ),
                ("hidden", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=False)),
                ("disabled", models.BooleanField(default=False)),
                ("tooltip", models.CharField(blank=True, max_length=255)),
                ("link", models.CharField(blank=True, max_length=255)),
                ("fragment", models.CharField(blank=True, max_length=255)),
                ("preserve_fragment", models.BooleanField(default=False)),
                ("query_params", models.TextField(blank=True)),
                ("query_params_handling", models.CharField(blank=True, max_length=255)),
                ("external_link", models.BooleanField(default=False)),
                (
                    "target",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("_blank", "Blank"),
                            ("_self", "Self"),
                            ("_parent", "Parent"),
                            ("_top", "Top"),
                        ],
                        max_length=255,
                    ),
                ),
                ("exact_match", models.BooleanField(default=False)),
                ("is_active_match_options", models.TextField(blank=True)),
                ("function", models.TextField(blank=True)),
                ("classes", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=255)),
                ("badge", models.TextField(blank=True)),
                ("meta", models.TextField(blank=True)),
                (
                    "children",
                    models.ManyToManyField(blank=True, to="navigation.navigation"),
                ),
                ("visible_to", models.ManyToManyField(blank=True, to="auth.group")),
            ],
            options={
                "verbose_name": "Navigation Item",
                "verbose_name_plural": "Navigation Items",
                "db_table": "navigations",
            },
        ),
        migrations.RemoveField(
            model_name="childnavigationbadge",
            name="Navigation",
        ),
        migrations.RemoveField(
            model_name="childnavigationclass",
            name="navigation",
        ),
        migrations.DeleteModel(
            name="ChildNavigation",
        ),
        migrations.DeleteModel(
            name="ChildNavigationBadge",
        ),
        migrations.DeleteModel(
            name="ChildNavigationClass",
        ),
        migrations.DeleteModel(
            name="MainNavigation",
        ),
    ]
