# Generated by Django 4.1.3 on 2022-12-18 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0003_alter_childnavigation_disabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childnavigation",
            name="main",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="navigation.mainnavigation",
            ),
        ),
    ]
