# Generated by Django 4.1.3 on 2022-12-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "navigation",
            "0003_navigation_remove_childnavigationbadge_navigation_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="navigation",
            name="icon",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="navigation",
            name="link",
            field=models.CharField(default="", max_length=255),
        ),
    ]
