# Generated by Django 4.1.3 on 2022-12-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0004_alter_childnavigation_main"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childnavigation",
            name="id",
            field=models.CharField(
                default="", max_length=50, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="mainnavigation",
            name="id",
            field=models.CharField(
                default="", max_length=50, primary_key=True, serialize=False
            ),
        ),
    ]
