# Generated by Django 4.1.3 on 2022-12-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0004_alter_navigation_icon_alter_navigation_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navigation",
            name="link",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
