# Generated by Django 4.1.3 on 2022-12-24 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("navigation", "0005_alter_navigation_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="navigation",
            name="children",
        ),
        migrations.RemoveField(
            model_name="navigation",
            name="visible_to",
        ),
        migrations.AddField(
            model_name="navigation",
            name="children",
            field=models.ForeignKey(
                blank=True,
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="navigation.navigation",
            ),
        ),
        migrations.AddField(
            model_name="navigation",
            name="visible_to",
            field=models.ForeignKey(
                blank=True,
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="auth.group",
            ),
        ),
    ]
