# Generated by Django 4.1.3 on 2022-12-24 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0006_remove_navigation_children_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navigation",
            name="children",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="navigation.navigation",
            ),
        ),
    ]
