# Generated by Django 4.1.3 on 2022-12-28 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("navigation", "0008_alter_navigation_visible_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="navigation",
            name="children",
        ),
        migrations.AddField(
            model_name="navigation",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="navigation.navigation",
            ),
        ),
        migrations.RemoveField(
            model_name="navigation",
            name="visible_to",
        ),
        migrations.AddField(
            model_name="navigation",
            name="visible_to",
            field=models.ManyToManyField(
                blank=True, default="", null=True, to="auth.group"
            ),
        ),
    ]
