# Generated by Django 4.1.3 on 2022-12-28 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0009_remove_navigation_children_navigation_parent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="navigation",
            name="parent",
        ),
        migrations.AddField(
            model_name="navigation",
            name="children",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="navigation.navigation",
            ),
        ),
    ]
