# Generated by Django 4.1.3 on 2022-12-28 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0010_remove_navigation_parent_navigation_children"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="navigation",
            name="children",
        ),
        migrations.AddField(
            model_name="navigation",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="navigation.navigation",
            ),
        ),
    ]
