# Generated by Django 4.1.3 on 2022-12-30 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("navigation", "0011_remove_navigation_children_navigation_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="navigation",
            name="visible_to",
        ),
        migrations.AddField(
            model_name="navigation",
            name="visible_to",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="auth.group",
            ),
        ),
    ]
