from .create import StaffCreateForm
from .address import StaffAddressForm
from .bank import StaffBankForm
from .contact import StaffContactForm
from .contract import StaffContractForm
from .detail import StaffDetailForm
from .education import StaffEducationForm
from .email import StaffEmailForm
from .employer import StaffEmployerForm
from .passort import StaffPassortForm
from .phone import StaffPhoneForm
from .appearance import StaffAppearanceForm
from .reference import StaffReferenceForm
from .health import StaffHealthForm
from .vetting import StaffVettingForm
