from .address import StaffAddressForm
from .appearance import StaffAppearanceForm
from .bank import StaffBankForm
from .contact import StaffContactForm
from .contract import StaffContractForm
from .create import StaffCreateForm
from .detail import StaffDetailForm
from .education import StaffEducationForm
from .email import StaffEmailForm
from .employer import StaffEmployerForm
from .health import StaffHealthForm
from .licence import StaffLicenceForm
from .passort import StaffPassortForm
from .phone import StaffPhoneForm
from .reference import StaffReferenceForm
from .vetting import StaffVettingForm
