# Generated by Django 4.2.1 on 2023-05-18 17:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=80)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='ClientPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='clients.client')),
            ],
            options={
                'verbose_name': 'Client Phone',
                'verbose_name_plural': 'Client Phones',
                'db_table': 'client_phone',
            },
        ),
        migrations.CreateModel(
            name='ClientNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20)),
                ('note', models.TextField(default='', max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='clients.client')),
            ],
            options={
                'verbose_name': 'Client Note',
                'verbose_name_plural': 'Client Notes',
                'db_table': 'client_notes',
            },
        ),
        migrations.CreateModel(
            name='ClientEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='clients.client')),
            ],
            options={
                'verbose_name': 'Client Email',
                'verbose_name_plural': 'Client Emails',
                'db_table': 'client_email',
            },
        ),
        migrations.CreateModel(
            name='ClientDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_number', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(max_length=100)),
                ('logo', models.CharField(blank=True, default='', max_length=255)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='clients.client')),
            ],
            options={
                'verbose_name': 'Client Detail',
                'verbose_name_plural': 'Client Detail',
                'db_table': 'client_detail',
            },
        ),
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=30)),
                ('post_code', models.CharField(max_length=15)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='clients.client')),
            ],
            options={
                'verbose_name': 'Client Address',
                'verbose_name_plural': 'Client Addresses',
                'db_table': 'client_address',
            },
        ),
    ]
