# Generated by Django 4.2.1 on 2023-05-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='rate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
