# Generated by Django 4.2.1 on 2023-05-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_baseuser_activation_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='activation_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
