# Generated by Django 4.2.1 on 2023-06-04 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_baseuser_activation_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='about',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='title',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=80)),
                ('phone', models.CharField(blank=True, default='', max_length=11)),
                ('about', models.TextField(blank=True, default='')),
                ('avatar', models.CharField(blank=True, default='', max_length=210, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profile',
            },
        ),
    ]
