# Generated by Django 4.2.6 on 2023-10-26 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("client", "0003_rename_address_client_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subcontractor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="", max_length=70)),
                ("email", models.EmailField(max_length=120, null=True)),
                ("mobile", models.CharField(default="", max_length=15)),
                ("land_line", models.CharField(max_length=15, null=True)),
                ("address", models.CharField(default="", max_length=150)),
                ("city", models.CharField(default="", max_length=20)),
                ("post_code", models.CharField(default="", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("reference", models.CharField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcontractors",
                        to="client.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subcontractor",
                "verbose_name_plural": "Subcontractors",
                "db_table": "subcontractor",
                "ordering": ("name",),
            },
        ),
    ]
