# Generated by Django 4.2.6 on 2023-10-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subcontractor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcontractor",
            name="pay_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
