# Generated by Django 4.2.7 on 2023-11-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subcontractor", "0002_subcontractor_pay_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcontractor",
            name="land_line",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="subcontractor",
            name="reference",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
