# Generated by Django 4.2.6 on 2023-10-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0001_initial"),
        ("shift", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="timesheet",
            old_name="date",
            new_name="shift_date",
        ),
        migrations.AlterField(
            model_name="shift",
            name="break_duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="timesheet",
            unique_together={("staff", "shift", "shift_date")},
        ),
    ]
