# Generated by Django 4.2.6 on 2023-10-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shift", "0002_rename_date_timesheet_shift_date_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="timesheet",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="timesheet",
            name="duration",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="timesheet",
            name="shift_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name="shift",
            table="shift",
        ),
    ]
