# Generated by Django 4.2.6 on 2023-10-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shift", "0003_alter_timesheet_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="timesheet",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
