# Generated by Django 4.2.6 on 2023-11-03 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("staff", "0002_staff_subcontractor"),
        ("shift", "0004_alter_shift_id_alter_timesheet_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("shift_date", models.DateField(blank=True, null=True)),
                ("duration", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_log",
                        to="shift.shift",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_log",
                        to="staff.staff",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_log",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Shift Log",
                "verbose_name_plural": "Shift Logs",
                "db_table": "shift_log",
            },
        ),
    ]
