# Generated by Django 4.2.6 on 2023-11-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shift", "0005_shiftlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftlog",
            name="action",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
