# Generated by Django 4.2.6 on 2023-11-03 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shift", "0006_shiftlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shiftlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shift_log",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
