# Generated by Django 4.2.7 on 2023-11-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shift", "0007_alter_shiftlog_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="time_in",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shift",
            name="time_out",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
