# Generated by Django 4.2.1 on 2023-05-31 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='name',
        ),
    ]
