# Generated by Django 4.2.1 on 2023-06-01 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_remove_shift_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ('time_in', 'time_out')},
        ),
    ]
