# Generated by Django 4.2.1 on 2023-06-01 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_alter_shift_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShiftSchedule',
        ),
    ]
