# Generated by Django 4.2.1 on 2023-06-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_delete_shiftschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
