# Generated by Django 4.2.1 on 2023-06-14 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_alter_staff_pay_rate'),
        ('shifts', '0005_shift_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='staff',
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField()),
                ('time_out', models.DateTimeField()),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesheet', to='shifts.shift')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesheet', to='staff.staff')),
            ],
            options={
                'ordering': ('time_in', 'time_out'),
            },
        ),
    ]
