# Generated by Django 4.2.1 on 2023-06-14 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0006_remove_shift_staff_timesheet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ('time_in', 'time_out'), 'verbose_name': 'Shift', 'verbose_name_plural': 'Shifts'},
        ),
        migrations.AlterModelOptions(
            name='timesheet',
            options={'ordering': ('time_in', 'time_out'), 'verbose_name': 'Timesheet', 'verbose_name_plural': 'Timesheets'},
        ),
        migrations.AlterModelTable(
            name='shift',
            table='shifts',
        ),
        migrations.AlterModelTable(
            name='timesheet',
            table='timesheets',
        ),
    ]
