from .create_customer import CreateCustomerForm
from .customer_details import CustomerDetailForm
from .customer_address import CustomerAddressForm
from .customer_other import CustomerPhoneForm, CustomerEmailForm, CustomerNoteForm