# Generated by Django 4.2.5 on 2023-09-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="Address",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AddField(
            model_name="client",
            name="city",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="client",
            name="land_line",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="mobile",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AddField(
            model_name="client",
            name="post_code",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="client",
            name="reference",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
