# Generated by Django 4.2.5 on 2023-09-18 13:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0002_client_address_client_city_client_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="Address",
            new_name="address",
        ),
    ]
