# Generated by Django 4.2.7 on 2023-11-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0003_rename_address_client_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="mobile",
            field=models.CharField(blank=True, default="", max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="reference",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
