# Generated by Django 4.1.3 on 2022-11-15 16:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="", max_length=70)),
                ("phone", models.CharField(default="", max_length=15)),
                ("mobile", models.CharField(default="", max_length=15)),
                ("address", models.CharField(default="", max_length=70)),
                ("city", models.CharField(default="", max_length=20)),
                ("post_code", models.CharField(default="", max_length=20)),
                ("email", models.CharField(default="", max_length=20)),
                ("status", models.BooleanField(default=False)),
            ],
        ),
    ]
