# Generated by Django 4.1.3 on 2022-11-19 17:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="", max_length=70)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ClientDetail",
            fields=[
                (
                    "client",
                    models.OneToOneField(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="detail",
                        serialize=False,
                        to="clients.client",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=70, null=True),
                ),
                (
                    "vat",
                    models.CharField(blank=True, default="", max_length=70, null=True),
                ),
                (
                    "website",
                    models.CharField(blank=True, default="", max_length=70, null=True),
                ),
                ("status", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="PhoneNumber",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "string",
                    models.CharField(blank=True, default="", max_length=30, null=True),
                ),
                (
                    "title",
                    models.CharField(blank=True, default="", max_length=30, null=True),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_numbers",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "PhoneNumbers",
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("string", models.CharField(default="", max_length=210)),
                (
                    "title",
                    models.CharField(blank=True, default="", max_length=30, null=True),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Notes",
            },
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "string",
                    models.CharField(blank=True, default="", max_length=30, null=True),
                ),
                (
                    "title",
                    models.CharField(blank=True, default="", max_length=30, null=True),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Emails",
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "detail",
                    models.OneToOneField(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="address",
                        serialize=False,
                        to="clients.clientdetail",
                    ),
                ),
                ("street", models.CharField(default="", max_length=210)),
                ("city", models.CharField(default="", max_length=30)),
                ("post_code", models.CharField(default="", max_length=30)),
            ],
        ),
    ]
