# Generated by Django 4.1.3 on 2022-11-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="id",
            field=models.CharField(
                default="", max_length=20, primary_key=True, serialize=False
            ),
        ),
    ]
