# Generated by Django 4.1.3 on 2022-11-16 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="city",
        ),
        migrations.RemoveField(
            model_name="client",
            name="email",
        ),
        migrations.RemoveField(
            model_name="client",
            name="mobile",
        ),
        migrations.RemoveField(
            model_name="client",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="client",
            name="post_code",
        ),
        migrations.AddField(
            model_name="client",
            name="display_name",
            field=models.CharField(blank=True, default="", max_length=70, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="vat",
            field=models.CharField(blank=True, default="", max_length=70, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="website",
            field=models.CharField(blank=True, default="", max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="address",
            field=models.CharField(default="", max_length=210),
        ),
        migrations.AlterField(
            model_name="client",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="phone_numbers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_emails",
                        to="clients.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_note",
                        to="clients.client",
                    ),
                ),
            ],
        ),
    ]
