# Generated by Django 4.1.3 on 2022-11-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_alter_client_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="id",
            field=models.CharField(
                default="", max_length=36, primary_key=True, serialize=False
            ),
        ),
    ]
