# Generated by Django 4.2.6 on 2023-10-26 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("subcontractor", "0001_initial"),
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="subcontractor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff",
                to="subcontractor.subcontractor",
            ),
        ),
    ]
