# Generated by Django 4.2.7 on 2023-11-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0002_staff_subcontractor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="staff",
            options={
                "ordering": ("first_name",),
                "verbose_name": "Staff",
                "verbose_name_plural": "Staff",
            },
        ),
        migrations.RemoveField(
            model_name="staff",
            name="name",
        ),
        migrations.AddField(
            model_name="staff",
            name="display_name",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AddField(
            model_name="staff",
            name="first_name",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AddField(
            model_name="staff",
            name="last_name",
            field=models.CharField(default="", max_length=30),
        ),
    ]
