# Generated by Django 4.2.7 on 2023-11-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0003_alter_staff_options_remove_staff_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="display_name",
            field=models.CharField(blank=True, default="", max_length=30, null=True),
        ),
    ]
