# Generated by Django 4.2.7 on 2023-11-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0002_location_charge_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="email",
            field=models.EmailField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="land_line",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="mobile",
            field=models.CharField(blank=True, default="", max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="reference",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
