# Generated by Django 4.2.1 on 2023-05-18 18:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=80)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='clients.client')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'db_table': 'sites',
            },
        ),
        migrations.CreateModel(
            name='SitePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='sites.site')),
            ],
            options={
                'verbose_name': 'Site Phone',
                'verbose_name_plural': 'Site Phones',
                'db_table': 'site_phone',
            },
        ),
        migrations.CreateModel(
            name='SiteNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20)),
                ('note', models.TextField(default='', max_length=255)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='sites.site')),
            ],
            options={
                'verbose_name': 'Site Note',
                'verbose_name_plural': 'Site Notes',
                'db_table': 'site_notes',
            },
        ),
        migrations.CreateModel(
            name='SiteEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='sites.site')),
            ],
            options={
                'verbose_name': 'Site Email',
                'verbose_name_plural': 'Site Emails',
                'db_table': 'site_email',
            },
        ),
        migrations.CreateModel(
            name='SiteAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=30)),
                ('post_code', models.CharField(max_length=15)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='sites.site')),
            ],
            options={
                'verbose_name': 'Site Address',
                'verbose_name_plural': 'Site Addresses',
                'db_table': 'site_address',
            },
        ),
    ]
