# Generated by Django 4.2.1 on 2023-05-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_site_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='rate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
