# Generated by Django 4.2.1 on 2023-06-01 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_site_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='rate',
            new_name='change_rate',
        ),
    ]
