# Generated by Django 4.2.1 on 2023-06-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_rename_rate_site_change_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ('name',), 'verbose_name': 'Site', 'verbose_name_plural': 'Sites'},
        ),
        migrations.RemoveField(
            model_name='site',
            name='change_rate',
        ),
        migrations.AddField(
            model_name='site',
            name='charge_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
