# Generated by Django 4.2.1 on 2023-06-01 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_alter_site_options_remove_site_change_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='customer',
        ),
    ]
