# Generated by Django 4.1.3 on 2022-12-22 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "username",
                    models.CharField(blank=True, default="", max_length=80, null=True),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, default="", max_length=80, null=True),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, default="", max_length=80, null=True),
                ),
                (
                    "avatar",
                    models.CharField(blank=True, default="", max_length=210, null=True),
                ),
                ("title", models.CharField(blank=True, default="", max_length=80)),
                ("phone", models.CharField(blank=True, default="", max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="", max_length=80)),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "db_table": "customers",
            },
        ),
        migrations.CreateModel(
            name="UserShortcuts",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(default="", max_length=50)),
                ("description", models.CharField(default="", max_length=100)),
                ("icon", models.CharField(default="", max_length=50)),
                ("link", models.CharField(default="", max_length=100)),
                ("useRouter", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shortcuts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User shortcut",
                "verbose_name_plural": "User shortcuts",
                "db_table": "user_shortcuts",
            },
        ),
        migrations.CreateModel(
            name="CustomerDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=100)),
                ("website", models.URLField(max_length=100)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="users.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Detail",
                "verbose_name_plural": "Customer Detail",
                "db_table": "customer_detail",
            },
        ),
        migrations.CreateModel(
            name="CustomerAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=30)),
                ("post_code", models.CharField(max_length=15)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address",
                        to="users.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Address",
                "verbose_name_plural": "Customer Addresses",
                "db_table": "customer_address",
            },
        ),
        migrations.CreateModel(
            name="AppConfig",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("layout", models.CharField(default="", max_length=25)),
                ("scheme", models.CharField(default="", max_length=25)),
                ("theme", models.CharField(default="", max_length=25)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "App config",
                "verbose_name_plural": "App configs",
                "db_table": "user_config",
            },
        ),
        migrations.AddField(
            model_name="baseuser",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="users.customer",
            ),
        ),
        migrations.AddField(
            model_name="baseuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="baseuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
