# Generated by Django 4.1.3 on 2022-12-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="baseuser",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AddField(
            model_name="baseuser",
            name="about",
            field=models.TextField(blank=True, default=""),
        ),
    ]
