# Generated by Django 4.1.3 on 2022-12-17 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customeraddress",
            options={
                "verbose_name": "Customer Address",
                "verbose_name_plural": "Customer Addresses",
            },
        ),
    ]
