# Generated by Django 4.1.3 on 2022-12-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_baseuser_options_baseuser_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerdetail",
            name="logo",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
