# Generated by Django 4.1.3 on 2022-12-17 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customeraddress_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customeraddress",
            name="customer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address",
                to="users.customer",
            ),
        ),
    ]
