# Generated by Django 4.1.3 on 2022-12-23 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customerdetail_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerdetail",
            name="email",
        ),
        migrations.RemoveField(
            model_name="customerdetail",
            name="phone",
        ),
        migrations.AddField(
            model_name="customerdetail",
            name="vat_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name="CustomerPhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=20)),
                ("phone", models.CharField(max_length=20)),
                (
                    "detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phones",
                        to="users.customerdetail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Phone",
                "verbose_name_plural": "Customer Phones",
                "db_table": "customer_phone",
            },
        ),
        migrations.CreateModel(
            name="CustomerNotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=20)),
                ("note", models.TextField(default="", max_length=255)),
                (
                    "detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="users.customerdetail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Note",
                "verbose_name_plural": "Customer Notes",
                "db_table": "customer_notes",
            },
        ),
        migrations.CreateModel(
            name="CustomerEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=20)),
                ("email", models.EmailField(max_length=100)),
                (
                    "detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="users.customerdetail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Email",
                "verbose_name_plural": "Customer Emails",
                "db_table": "customer_email",
            },
        ),
    ]
