# Generated by Django 4.1.3 on 2022-12-18 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customeraddress_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserShortcuts",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(default="", max_length=50)),
                ("description", models.CharField(default="", max_length=100)),
                ("icon", models.CharField(default="", max_length=50)),
                ("link", models.CharField(default="", max_length=100)),
                ("useRouter", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shortcuts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_shortcuts",
            },
        ),
    ]
