# Generated by Django 4.1.3 on 2022-12-23 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_customerdetail_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerdetail",
            name="customer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detail",
                to="users.customer",
            ),
        ),
    ]
