# Generated by Django 4.1.3 on 2022-12-18 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_usershortcuts"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usershortcuts",
            options={
                "verbose_name": "User shortcut",
                "verbose_name_plural": "User shortcuts",
            },
        ),
    ]
