# Generated by Django 4.1.3 on 2022-12-23 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_customerdetail_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customeremail",
            name="detail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_emails",
                to="users.customerdetail",
            ),
        ),
        migrations.AlterField(
            model_name="customernotes",
            name="detail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_notes",
                to="users.customerdetail",
            ),
        ),
        migrations.AlterField(
            model_name="customerphone",
            name="detail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_phones",
                to="users.customerdetail",
            ),
        ),
    ]
