# Generated by Django 4.1.3 on 2022-12-19 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_usershortcuts_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("layout", models.CharField(default="", max_length=25)),
                ("scheme", models.CharField(default="", max_length=25)),
                ("theme", models.CharField(default="", max_length=25)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "App config",
                "verbose_name_plural": "App configs",
            },
        ),
        migrations.CreateModel(
            name="Themes",
            fields=[
                (
                    "id",
                    models.CharField(
                        default="", max_length=25, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(default="", max_length=25)),
                (
                    "app_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="themes",
                        to="users.appconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Theme",
                "verbose_name_plural": "Themes",
            },
        ),
        migrations.CreateModel(
            name="Screens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sm", models.CharField(default="", max_length=25)),
                ("md", models.CharField(default="", max_length=25)),
                ("lg", models.CharField(default="", max_length=25)),
                ("xl", models.CharField(default="", max_length=25)),
                (
                    "app_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screens",
                        to="users.appconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Screen",
                "verbose_name_plural": "Screens",
            },
        ),
    ]
