# Generated by Django 4.1.3 on 2022-12-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_appconfig_themes_screens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseuser",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="baseuser",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=80, null=True),
        ),
    ]
