# Generated by Django 4.1.3 on 2022-12-28 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_customeremail_detail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customeremail",
            name="detail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emails",
                to="users.customerdetail",
            ),
        ),
        migrations.AlterField(
            model_name="customernotes",
            name="detail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="users.customerdetail",
            ),
        ),
        migrations.AlterField(
            model_name="customerphone",
            name="detail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phones",
                to="users.customerdetail",
            ),
        ),
    ]
