# Generated by Django 4.1.3 on 2022-12-19 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_baseuser_first_name_alter_baseuser_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseuser",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="users.customer",
            ),
        ),
    ]
