# Generated by Django 4.1.3 on 2022-12-19 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_baseuser_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usershortcuts",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shortcuts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
