# Generated by Django 4.1.3 on 2022-12-21 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_usershortcuts_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=100)),
                ("website", models.URLField(max_length=100)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="users.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Detail",
                "verbose_name_plural": "Customer Detail",
            },
        ),
        migrations.RemoveField(
            model_name="themes",
            name="app_config",
        ),
        migrations.AlterField(
            model_name="appconfig",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name="Screens",
        ),
        migrations.DeleteModel(
            name="Themes",
        ),
    ]
